---
- name: Pull, modify, and push Docker container between environments
  hosts: production_server
  become: yes  # Use this if you need to run commands as a sudo user
  tasks:
    - name: Ensure Docker is installed on production server
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Commit the running container to a new image
      command: docker commit prod_nginx prod_nginx:latest

    - name: Export the Docker image to a tar file
      command: docker save -o /tmp/prod_nginx.tar prod_nginx:latest
        
    - name: Set read permissions on the Docker image tar file
      file:
        path: /tmp/prod_nginx*.tar
        mode: '0644'
        owner: root
        group: root
        
    - name: Archive docker volume
      archive:
        path: /var/lib/html/*
        dest: /tmp/prod_nginx_volume.tar
        
    - name: Copy the volume tar to the local machine
      fetch:
        src: /tmp/prod_nginx_volume.tar
        dest: /tmp/prod_nginx_volume.tar
        flat: yes
        
    - name: Copy the exported container tar to the local machine
      fetch:
        src: /tmp/prod_nginx.tar
        dest: /tmp/prod_nginx.tar
        flat: yes

    - name: Clean up the container tar archive from the production server
      file:
        path: /tmp/prod_nginx.tar
        state: absent
        
    - name: Clean up the volume tar archive from the production server
      file:
        path: /tmp/prod_nginx_volume.tar
        state: absent
