---
- name: Pull and Modify NGINX Docker Site
  hosts: production_server
  become: yes  # Use this if you need to run commands as a sudo user
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"
      
    - name: Stop and remove existing container if present
      docker_container:
        name: prod_nginx
        state: absent 
        
    - name: Create a directory
      file:
        path: /var/lib/html/
        state: directory
        mode: '0755'
        
    - name: Pull NGINX Docker image
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: Create custom index.html
      copy:
        src: html/prod_index.html
        dest: /var/lib/html/index.html
        mode: '0644'

    - name: Run NGINX Docker container
      community.docker.docker_container:
        name: prod_nginx
        image: nginx:latest
        state: started
        ports:
          - "8080:80"
        volumes:
          - /var/lib/html:/usr/share/nginx/html
          
    - name: Set permissions on a folder
      file:
        path: /usr/share/nginx/html
        owner: root
        group: root
        mode: '0755'
        state: directory
        recurse: no  # Apply permissions recursively to all files and directories          

    - name: Verify NGINX container is running
      community.docker.docker_container_info:
        name: prod_nginx
      register: nginx_container_info

