---
- name: Pull and Run Docker Container
  hosts: all
  become: yes  # Use this if you need to run commands as a sudo user
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Pull Docker image
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: my_nginx
        image: nginx:latest
        state: started
        ports:
          - "8080:80"
