---
- name: Pull and Modify NGINX Docker Site
  hosts: all
  become: yes  # Use this if you need to run commands as a sudo user
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Pull NGINX Docker image
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: Create custom index.html
      copy:
        dest: html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to Custom NGINX!</title>
          </head>
          <body>
              <h1>Success! Custom NGINX server is running.</h1>
          </body>
          </html>

    - name: Run NGINX Docker container
      community.docker.docker_container:
        name: custom_nginx
        image: nginx:latest
        state: started
        ports:
          - "8080:80"
        volumes:
          - html:/usr/share/nginx/html

    - name: Verify NGINX container is running
      community.docker.docker_container_info:
        name: custom_nginx
      register: nginx_container_info

    - debug:
        var: nginx_container_info
