---
- name: Pull data from a running Docker container
  hosts: all
  become: yes  # Use this if you need to run commands as a sudo user
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Save container filesystem as an archive
      command: docker export prod_nginx -o /tmp/prod_nginx.tar
      args:
        chdir: /tmp

    - name: Commit running container to a new image
      community.docker.docker_image:
        name: prod_nginx
        tag: latest
        container: prod_nginx
        source: commit

    - name: Copy the saved filesystem archive to the local machine
      fetch:
        src: /tmp/prod_nginx.tar
        dest: ./prod_nginx.tar
        flat: yes

    - name: Clean up the archive from the remote host
      file:
        path: /tmp/prod_nginx.tar
        state: absent
